#!/bin/bash

clear

echo " Starting Full Update. "
sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade && sudo apt-get -y autoremove &&
clear
echo " Full Update Complete. "
exit
